// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1) {
  return window['go']['service']['DownloadService']['DownloadFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['service']['DownloadService']['Startup'](arg1);
}
