// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['service']['SysService']['ChooseDirectory']();
}

export function GetConfig() {
  return window['go']['service']['SysService']['GetConfig']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['service']['SysService']['SaveConfig'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['service']['SysService']['Startup'](arg1);
}
