// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function ChooseDirectory():Promise<string>;

export function GetConfig():Promise<model.SysConfig>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
