// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"JetGet/backend/app"
	"JetGet/backend/config/db"
	"JetGet/backend/service"
)

// Injectors from wire.go:

// InitializeApp 使用 Wire 来构建和初始化整个应用。
// 它会返回一个包含所有服务和配置的 App 结构体。
func InitializeApp() (*app.App, error) {
	gormDB, err := db.ProvideDB()
	if err != nil {
		return nil, err
	}
	hostId, err := db.ProvideHostID()
	if err != nil {
		return nil, err
	}
	sysService := service.NewSysService(gormDB, hostId)
	downloadService := service.NewDownloadService(gormDB, hostId, sysService)
	appApp := app.NewApp(sysService, downloadService)
	return appApp, nil
}
